---
ssrs_url: https://download.microsoft.com/download/1/a/a/1aaa9177-3578-4931-b8f3-373b24f63342/SQLServerReportingServices.exe
scom_2022_url: https://download.microsoft.com/download/4/8/d/48da839e-0317-49ed-8c6a-ae534e598db2/SCOM_2022.exe?culture=en-us&country=US


scom_management_server: scom-om1   
scom_omreporting_send_odr_reports: 0      # [0|1]
scom_omreporting_use_microsoft_update: 0  # [0|1]